spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pub-manager-db-instance.ckebdlupk2xi.ap-northeast-2.rds.amazonaws.com:3306/pub_manager_db?characterEncoding=UTF-8
    username: admin
    password: pub20231107!